"""PostFile表增加type(文件类型)列

Revision ID: 1f7ad13142b4
Revises: 6fb6f5e87934
Create Date: 2019-12-13 14:57:33.682038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f7ad13142b4'
down_revision = '6fb6f5e87934'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_file', sa.Column('type', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post_file', 'type')
    # ### end Alembic commands ###
